name: pull-request-opened

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show message
        run: |
          echo "pull-${{ github.event.pull_request.number }}: opened"
